name: Create release pull request
on:
  push:
    branches:
      - develop
      - staging
jobs:
  create-release-pr-staging:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: contains(github.ref, 'develop')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: fetch
        run: git fetch origin staging:staging
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: git-pr-release
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: staging
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_LABELS: 'release: test'
        run: |
          gem install -N git-pr-release -v "1.9.0"
          git-pr-release --no-fetch
